export enum UserRoles {
  USER_ROLE_GUEST = 'USER_ROLE_GUEST',
  USER_ROLE_EXTERNAL_REQUESTER = 'USER_ROLE_EXTERNAL_REQUESTER',
  USER_ROLE_INTERNAL_REQUESTER = 'USER_ROLE_INTERNAL_REQUESTER',
  USER_ROLE_INTERNAL_MANAGER = 'USER_ROLE_INTERNAL_MANAGER',
  USER_ROLE_INTERNAL_ADMIN = 'USER_ROLE_INTERNAL_ADMIN',
  USER_ROLE_ROOT_ADMIN = 'USER_ROLE_ROOT_ADMIN',
}

export const SIGN_UP_ATTEMPT = 'SIGN_UP_ATTEMPT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
